os: linux
dist: xenial
group: travis_latest
addons:
  apt:
    packages:
      - docker-ce
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
if: |
  branch = master AND ! commit_message =~ /README.md/ AND ! commit_message =~ /docker-compose.yml/
  OR type = cron

language: shell

services:
  - docker

install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - mkdir -p ./travis
  - curl -ksSl -o ./travis/enable-experimental-docker.sh "https://raw.githubusercontent.com/ShoGinn/docker-builds/master/travis/enable-experimental-docker.sh"
  - curl -ksSl -o ./travis/build.sh "https://raw.githubusercontent.com/ShoGinn/docker-builds/master/travis/build.sh"
  - curl -ksSl -o ./travis/deploy.sh "https://raw.githubusercontent.com/ShoGinn/docker-builds/master/travis/deploy.sh"
  - curl -ksSl -o ./travis/success.sh "https://raw.githubusercontent.com/ShoGinn/docker-builds/master/travis/success.sh"
  - sudo chmod +x ./travis/*.sh
  - sudo travis/enable-experimental-docker.sh
  - sudo docker version
  - if test -f .travis_env; then set -o allexport; source .travis_env; set +o allexport; fi
  - sudo env

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' dockerfiles/*
  - chmod 0544 rootfs/usr/local/bin/docker_entrypoint.sh


script:
  - travis/build.sh

deploy:
  provider: script
  script: travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - travis/success.sh

notifications:
  email:
    on_success: never
    on_failure: change

# Repo Specific
env:
  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - DOCKER_MAINTAINER="shoginn"
    - DOCKER_URL="https://shoginn.github.io"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"

  jobs:
    - DOCKER_TAG="latest"
